import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import CmsNavbar from "@/components/studio/Navbar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <CmsNavbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
